name: FTs
on:
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      # See https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/10
      - "**:**"
jobs:
  create-and-store-binaries:
    name: Create and store binaries for all platforms
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Create plugin binaries on all platforms
        run: |
          go run build/make.go --all-platforms && go run build/make.go --distro --all-platforms

      - name: Store plugin binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries-all-platforms
          path: bin/distros/

  functional-tests:
    name: ${{ matrix.confluence-version }} ${{ matrix.os }} FTs
    runs-on: ${{ matrix.os }}
    needs: [create-and-store-binaries]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        confluence-version: [Cloud]
        include:
          - confluence-version: Cloud
            confluence-base-url: CONFLUENCE_CLOUD_BASE_URL
            confluence-username: CONFLUENCE_CLOUD_USERNAME
            confluence-token: CONFLUENCE_CLOUD_TOKEN
            gauge-tags: "!not-cloud"
            
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "15" # Need minimum Java 15 for text blocks in functional tests

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master
          gauge-plugins: java, html-report, screenshot

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-all-platforms
          path: ${{ runner.temp }}

      - name: Install plugin (windows)
        working-directory: ${{ runner.temp }}
        if: matrix.os == 'windows-latest'
        run: |
          gauge install confluence --file $(dir *windows.x86_64.zip)

      - name: Install plugin (linux)
        working-directory: ${{ runner.temp }}
        if: matrix.os == 'ubuntu-latest'
        run: |
          gauge install confluence --file $(ls -d *linux.x86_64.zip)

      - name: Install plugin (macos)
        working-directory: ${{ runner.temp }}
        if: matrix.os == 'macos-latest'
        run: |
          gauge install confluence --file $(ls -d *darwin.x86_64.zip)

      - name: FTs ${{ matrix.confluence-version }} linux or osx
        if: matrix.os != 'windows-latest'
        env:
          CONFLUENCE_BASE_URL: ${{ secrets[matrix.confluence-base-url] }}
          CONFLUENCE_USERNAME: ${{ secrets[matrix.confluence-username] }}
          CONFLUENCE_TOKEN: ${{ secrets[matrix.confluence-token] }}
          CONFLUENCE_USERNAME_WITHOUT_CREATE_SPACE: ${{ secrets[matrix.confluence-username-without-create-space] }}
          CONFLUENCE_TOKEN_WITHOUT_CREATE_SPACE: ${{ secrets[matrix.confluence-token-without-create-space] }}
        run: |
          cd functional-tests
          ./gradlew clean ft -Ptags=${{ matrix.gauge-tags }}

      - name: FTs ${{ matrix.confluence-version }} windows
        if: matrix.os == 'windows-latest'
        env:
          CONFLUENCE_BASE_URL: ${{ secrets[matrix.confluence-base-url] }}
          CONFLUENCE_USERNAME: ${{ secrets[matrix.confluence-username] }}
          CONFLUENCE_TOKEN: ${{ secrets[matrix.confluence-token] }}
          CONFLUENCE_USERNAME_WITHOUT_CREATE_SPACE: ${{ secrets[matrix.confluence-username-without-create-space] }}
          CONFLUENCE_TOKEN_WITHOUT_CREATE_SPACE: ${{ secrets[matrix.confluence-token-without-create-space] }}
        run: |
          cd functional-tests
          .\gradlew.bat clean ft -Ptags=${{ matrix.gauge-tags }}
        shell: pwsh

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ft-logs-${{ matrix.confluence-version }}-${{ matrix.os }}
          path: functional-tests/logs
