name: Store distros
on: push
jobs:

  distro:
    name: Store distros 
    runs-on: ubuntu-latest
      
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master

      - name: Create plugin binaries on all platforms
        run: |
          go run build/make.go --all-platforms && go run build/make.go --distro --all-platforms

      - name: Store plugin binaries
        uses: actions/upload-artifact@v2
        with:
          name: gauge-confluence-binaries-all-platforms
          path: bin/distros/
